apiVersion: v1
kind: Service
metadata:
  name: manageservice-ingress
spec:
  type: NodePort 
  ports:
  - port: 8080
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: manageservice-ingress
